name       : python-google-api-core
version    : 2.8.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/52/9e/c2f8458c4ca67b2b1b88b3b4b04dd5513b188eec300089ada2cb56ba8ff3/google-api-core-2.8.0.tar.gz : 065bb8e11c605fd232707ae50963dc1c8af5b3c95b4568887515985e6c1156b3
license    : Apache-2.0
component  : programming.python
summary    : Google API client core library
description: |
    This library is not meant to stand-alone. Instead it defines common helpers used by all Google API clients.
rundeps    :
    - python-google-auth
    - python-googleapis-common-protos
    - python-pytz
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
